spring:
  # DATABASE
  datasource:
    hikari:
      leak-detection-threshold: ${DB_LEAK_THRESHOLD:2000}

  # ORM / Hibernate
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.flywaydb: DEBUG
    com.achernov.cryptoarb: DEBUG

app:
  cookie:
    secure: false
  cors:
    allowed-origins:
      - "http://localhost:5173"
      - "http://127.0.0.1:5173"
