CREATE TABLE refresh_tokens
(
  id          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  token       VARCHAR(255) NOT NULL UNIQUE,
  user_id     BIGINT       NOT NULL,
  expiry_date TIMESTAMP,
  CONSTRAINT fk_refresh_token_user FOREIGN KEY (user_id) REFERENCES users (id)
);
